name: supabase_app_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  animate_do: ^3.3.4
  get: 4.6.6
  flutter_dotenv: ^5.1.0
  form_validator: ^2.1.1
  supabase_flutter: ^1.10.16
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  uuid: ^4.0.0
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  flutter_facebook_auth: ^6.2.0
  firebase_auth: ^4.17.4
  flutter_web_auth: ^0.5.0
  swipe_to: ^1.0.6
  video_thumbnail: ^0.5.3
  clipboard: ^0.1.3
  flutter_chat_reactions: ^0.1.0
  timeago :
  flutter_image_compress: ^2.0.4
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  syncfusion_flutter_pdfviewer: ^26.1.42
  video_player: ^2.9.1
  chewie: ^1.8.3
  flutter_pdfview: ^1.3.2
  pdf: ^3.11.1
  jiffy: ^6.2.1
  lottie: ^2.3.2
  flutter_svg: ^1.1.3
  shared_preferences: ^2.0.15
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^2.3.6
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.9.0
  change_app_package_name: ^1.1.0
  intl: ^0.19.0
  fpdart: ^1.1.0
  graphview: ^1.2.0
  country_picker: ^2.0.26
  msh_checkbox: ^2.0.1
  insta_image_viewer: ^1.0.4
  flutter_hooks: ^0.18.5+1
  file_picker: ^6.0.0
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.2.6
  photo_view: ^0.15.0
  device_info_plus: ^10.0.1
  emoji_picker_flutter: ^1.5.1
  agora_rtc_engine: ^6.2.4
  agora_uikit: ^1.3.7
  stream_d: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/animation/
    - assets/icons/
    - assets/images/
    - .env
